export default defineEventHandler(() => {
  return [
    {
      id: "RT3080",
      title: "Brand Guidelines",
      invoiceDate: "18 Aug 2021",
      paymentDue: "19 Aug 2021",
      dueDate: "19 Aug 2021",
      clientName: "Jensen Huang",
      clientEmail: "jensenh@example.com",
      amount: "$1,800.90",
      status: "paid",
      senderAddress: {
        street: "71 Tottenham Court Road",
        city: "London",
        postCode: "W1T 4QW",
        country: "United Kingdom",
      },
      clientAddress: {
        street: "33 Hartfield Road",
        city: "London",
        postCode: "SW19 3RQ",
        country: "United Kingdom",
      },
      to: "/invoices/RT3080",
    },
    {
      id: "XM9141",
      title: "Graphic Design",
      invoiceDate: "21 Aug 2021",
      paymentDue: "20 Sep 2021",
      dueDate: "20 Aug 2021",
      clientName: "Alex Grim",
      clientEmail: "alexgrim@mail.com",
      amount: "$556.00",
      status: "pending",
      senderAddress: {
        street: "19 Union Terrace",
        city: "London",
        postCode: "E1 3EZ",
        country: "United Kingdom",
      },
      clientAddress: {
        street: "84 Church Way",
        city: "Bradford",
        postCode: "BD1 9PB",
        country: "United Kingdom",
      },
      to: "/invoices/XM9141",
    },
    {
      id: "RG0314",
      title: "Website Redesign",
      invoiceDate: "28 Aug 2021",
      paymentDue: "01 Sep 2021",
      dueDate: "01 Sep 2021",
      clientName: "John Morrison",
      clientEmail: "john.morrison@example.com",
      amount: "$14,002.33",
      status: "draft",
      senderAddress: {
        street: "10 Broad Street",
        city: "Birmingham",
        postCode: "B1 2HF",
        country: "United Kingdom",
      },
      clientAddress: {
        street: "28 Canal Street",
        city: "Leeds",
        postCode: "LS1 5PS",
        country: "United Kingdom",
      },
      to: "/invoices/RG0314",
    },
    {
      id: "RT2080",
      title: "Landing Page Copy",
      invoiceDate: "08 Sep 2021",
      paymentDue: "12 Sep 2021",
      dueDate: "12 Sep 2021",
      clientName: "Samantha Lee",
      clientEmail: "samantha.lee@example.com",
      amount: "$1,024.00",
      status: "paid",
      senderAddress: {
        street: "84 King Street",
        city: "Manchester",
        postCode: "M2 4WQ",
        country: "United Kingdom",
      },
      clientAddress: {
        street: "9 Park Lane",
        city: "Manchester",
        postCode: "M3 1HZ",
        country: "United Kingdom",
      },
      to: "/invoices/RT2080",
    },
    {
      id: "AA1449",
      title: "Mobile App Screens",
      invoiceDate: "10 Sep 2021",
      paymentDue: "14 Sep 2021",
      dueDate: "14 Sep 2021",
      clientName: "Oliver Grant",
      clientEmail: "oliver.grant@example.com",
      amount: "$3,110.44",
      status: "pending",
      senderAddress: {
        street: "5 Queen Square",
        city: "Bristol",
        postCode: "BS1 4NT",
        country: "United Kingdom",
      },
      clientAddress: {
        street: "42 Victoria Street",
        city: "Bath",
        postCode: "BA1 1BP",
        country: "United Kingdom",
      },
      to: "/invoices/AA1449",
    },
    {
      id: "TY9141",
      title: "Illustration Set",
      invoiceDate: "15 Sep 2021",
      paymentDue: "18 Sep 2021",
      dueDate: "18 Sep 2021",
      clientName: "Emily Carter",
      clientEmail: "emily.carter@example.com",
      amount: "$670.12",
      status: "draft",
      senderAddress: {
        street: "22 Rose Lane",
        city: "Liverpool",
        postCode: "L1 9BX",
        country: "United Kingdom",
      },
      clientAddress: {
        street: "14 Bold Street",
        city: "Liverpool",
        postCode: "L2 1DS",
        country: "United Kingdom",
      },
      to: "/invoices/TY9141",
    },
    {
      id: "FV2353",
      title: "Marketing Assets",
      invoiceDate: "20 Sep 2021",
      paymentDue: "24 Sep 2021",
      dueDate: "24 Sep 2021",
      clientName: "Janet Weiss",
      clientEmail: "janet.weiss@example.com",
      amount: "$2,350.00",
      status: "paid",
      senderAddress: {
        street: "43 George Street",
        city: "Edinburgh",
        postCode: "EH2 2HT",
        country: "United Kingdom",
      },
      clientAddress: {
        street: "58 Princes Street",
        city: "Edinburgh",
        postCode: "EH2 2DG",
        country: "United Kingdom",
      },
      to: "/invoices/FV2353",
    },
  ];
});